### ISSUE TITLE
Wiring

### ISSUE THREAD

**Issue by developerfromjokela** [latonita/jeep-canbus#4]
Hello!

How do you actually wire this in and get AUX working?

**Comment by latonita** [comment]
Not really sure I got the question, but most of signals come from the wide connector on the back of the radio unit.
I have just soldered wires from inside of the radio to that connector. I can't tell exact pinout at the moment, you might need to google it.
So...
1. CAN H/CAN L - from the wide connector, pins 15,16
2. AUX IN R/L - also on the wide connector, pins 4 & 8. (VES IN R/L), pin 7  VES IN GND
3. Power - similar
4. for my super-overengineered with extra features
4.1. I also use some signal which took somewhere on the left part of the board which indicates whether radio in turned on or off by the left knob - this is used to turn on my MCU and bluetooth module to avoid any issues/glitches
4.2. on a can bus i also listen whether next/prev track button is pressed

@developerfromjokela  does this answers your question? 

![Radio connector pinout](https://raw.githubusercontent.com/latonita/jeep-canbus/master/jeep%20WH%20radio%20pinout.jpg)

**Comment by developerfromjokela** [comment]
Yes it does.

Is the Can bus + High or low cable of canbus?

**Comment by latonita** [comment]
Apologies :) Terminology differs a bit in different documents. Typically they use HIGH/LOW but on this picture they put + and - instead of H and L
So basically CAN+, CAN HIGH, CAN H refers to the same.
Similarly -> CAN-, CAN LOW, CAN L are the same thing.
